name: Android Build & Deploy
 
on:
 push:
   branches:
     - main
 
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v2
 
   - name: Install Java
     uses: actions/setup-java@v3
     with:
      java-version: 17
      distribution: adopt
      cache: gradle

   - name: Validate Gradle wrapper
     uses: gradle/wrapper-validation-action@v1
   
   - name: Set up ruby env
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: 3.3.5
       bundler-cache: true

   - name: Setup Node 
     uses: actions/setup-node@v3
     with:
       node-version: '22.11.0'
    
   - name: Install node modules
     run: npm install
  
   - name: Decode Service Account Key JSON File
     uses: timheuer/base64-to-file@v1.2
     id: service_account_json_file
     with:
       fileName: "serviceAccount.json"
       encodedString: ${{ secrets.GOOGLE_PLAY_JSON_FILE }}
 
   - name: Decode Keystore File
     uses: timheuer/base64-to-file@v1.2
     id: android_keystore
     with:
       fileName: "android_keystore.keystore"
       encodedString: ${{ secrets.ANDROID_SIGNING_KEY_FILE }}
 
   - name: Build & deploy Android release
     run: bundle exec fastlane android deploy
     env:
       ANDROID_SIGNING_KEY_FILE: ${{ steps.android_keystore.outputs.filePath }}
       ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
       ANDROID_SIGNING_KEY_ALIAS: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
       ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
       FIREBASE_APP_TOKEN: ${{ secrets.FIREBASE_APP_TOKEN }}
       FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       GOOGLE_PLAY_JSON_FILE: ${{ steps.service_account_json_file.outputs.filePath }}
 
   - name: Upload build artifacts
     uses: actions/upload-artifact@v4
     with:
       name: assets
       path: |
         ${{ github.workspace }}/app/build/outputs/bundle/release